add_newline = false
# command_timeout = 3000

[character]
success_symbol = "ğŸ¦„ " 
error_symbol = "ğŸ¥º "

[git_status]
style = "bold white"
conflicted = " ğŸ³"
ahead = " ğŸğŸ’¨ "
behind =" ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤·â€ "
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green)'
renamed = " ğŸ‘… "
deleted = " ğŸ—‘ "

[gcloud]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
