add_newline = false

[character]
success_symbol = "ğŸ¦„ " 
error_symbol = "ğŸ¥º "

[git_branch]
symbol = "ğŸŒ± "

[git_status]
style = "bold white"
conflicted = " ğŸ³"
ahead = " ğŸğŸ’¨ "
behind =" ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤·â€ "
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green)'
renamed = " ğŸ‘… "
deleted = " ğŸ—‘ "
